In [1]:
import numpy as np

In [2]:
array1=np.array([22,55,61])
print(array1)

[22 55 61]


In [3]:
array2=np.array([[44,55,20,],[21,56,12]])
print(array2)

[[44 55 20]
 [21 56 12]]


In [4]:
(array1[~(array1<5)])

array([22, 55, 61])

In [5]:
array1[(array1>5)& (array1 %2 == 0)]

array([22])

In [6]:
array1[array1 %2 == 0]

array([22])

In [7]:
array1[(array1>5)| (array1 %2 == 0)]

array([22, 55, 61])

In [8]:
array1[(array1>5)& ~(array1 %2 == 0)]

array([55, 61])

In [9]:
array1[-2]

np.int64(55)

In [10]:
array1[0:2]

array([22, 55])

In [11]:
array2[0,1]

np.int64(55)

In [12]:
array2[0:,0:2]

array([[44, 55],
       [21, 56]])

In [13]:
array2[0:,2]

array([20, 12])

In [14]:
array2[0,1:]

array([55, 20])

In [15]:
array2

array([[44, 55, 20],
       [21, 56, 12]])

In [16]:
array3=np.array([[[1,2,3,4],[5,4,8,9],[7,8,1,4]],[[1,4,7,8],[1,2,3,4],[0,4,8,9]]])
print(array3)

[[[1 2 3 4]
  [5 4 8 9]
  [7 8 1 4]]

 [[1 4 7 8]
  [1 2 3 4]
  [0 4 8 9]]]


In [17]:
array3[0,2,2]

np.int64(1)

In [18]:
array3[0:2,1:3,1:]

array([[[4, 8, 9],
        [8, 1, 4]],

       [[2, 3, 4],
        [4, 8, 9]]])

In [19]:
array1=np.array([22,55,61])
print(array1)

[22 55 61]


In [20]:
array0=np.array([[44,88,99,],[23,41,33]])
print(array0)

[[44 88 99]
 [23 41 33]]


In [21]:
array0[(array0>5)& ~(array0 % 2==0)]

array([99, 23, 41, 33])

In [22]:
array0[array0 % 2== 0]

array([44, 88])

In [23]:
array0[(array0>5)|(array0 % 2==0)]

array([44, 88, 99, 23, 41, 33])

In [24]:
array0[(array0>5)& ~(array0 % 2==0)]

array([99, 23, 41, 33])

In [25]:
array0[-2]

array([44, 88, 99])

In [26]:
array0[0:2]

array([[44, 88, 99],
       [23, 41, 33]])

In [27]:
array0[0,1]

np.int64(88)

In [28]:
array0[0:,0:2]

array([[44, 88],
       [23, 41]])

In [29]:
array0[0:,2]

array([99, 33])

In [30]:
array0[0,1:]

array([88, 99])

In [31]:
array01=np.array([[[21,23,23],[10,55,33],[11,22,33]],[[11,22,33],[12,33,45],[10,41,55]]])
print(array01)

[[[21 23 23]
  [10 55 33]
  [11 22 33]]

 [[11 22 33]
  [12 33 45]
  [10 41 55]]]


In [32]:
array01[0,2,2]

np.int64(33)

In [33]:
array01[0:2,1:3,1:]

array([[[55, 33],
        [22, 33]],

       [[33, 45],
        [41, 55]]])

In [43]:
#array2[[0,1],[0,1]]

array([44, 56])

In [39]:
array2

array([[44, 55, 20],
       [21, 56, 12]])

In [44]:
array1.sum()

np.int64(138)

In [65]:
array2.sum()

np.int64(208)

In [66]:
array2.sum(axis=0)

array([ 65, 111,  32])

In [67]:
array2.sum(axis=1)

array([119,  89])

In [45]:
array2.prod()

np.int64(683020800)

In [47]:
array1.min()

np.int64(22)

In [48]:
array1.max()

np.int64(61)

In [50]:
np.log(array1)

array([3.09104245, 4.00733319, 4.11087386])

In [51]:
np.round(array1)

array([22, 55, 61])

In [52]:
np.exp(array1)

array([3.58491285e+09, 7.69478527e+23, 3.10429794e+26])

In [53]:
#statistical functions
np.mean(array1)

np.float64(46.0)

In [54]:
np.median(array1)

np.float64(55.0)

In [56]:
np.std(array1)

np.float64(17.146428199482248)

In [57]:
np.var(array1)

np.float64(294.0)

In [62]:
np.percentile(array1,30)

np.float64(41.8)

In [64]:
np.quantile(array1,0.30)

np.float64(41.8)

In [68]:
array1.sort()

In [70]:
array1

array([22, 55, 61])

In [71]:
array2.sort()

In [72]:
array2

array([[20, 44, 55],
       [12, 21, 56]])

In [73]:
array1.argmin()

np.int64(0)

In [74]:
array1.argmax()

np.int64(2)

In [75]:
array1.argsort()

array([0, 1, 2])

In [82]:
ar=np.array([56,78,23])

In [83]:
ar.argsort()

array([2, 0, 1])

In [78]:
ar.sort()

In [79]:
ar

array([23, 56, 78])

In [80]:
ar.argsort()

array([0, 1, 2])

In [85]:
array2

array([[20, 44, 55],
       [12, 21, 56]])

In [84]:
array2.argmin()

np.int64(3)