In [ ]:
import numpy as np

In [ ]:
arr1=np.array([5,6,7,8],dtype=float)

In [ ]:
arr1

array([5., 6., 7., 8.])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:

arr2= np.array([[5,6,7],[3,4,5],[1,2,3]])
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr3=np.array([[[5,6,7],[3,4,5],[1,2,3]],[[56,89,45],[77,33,55],[12,23,34]]])
arr3

array([[[ 5,  6,  7],
        [ 3,  4,  5],
        [ 1,  2,  3]],

       [[56, 89, 45],
        [77, 33, 55],
        [12, 23, 34]]])

In [ ]:
print(arr1.ndim, arr2.ndim,arr3.ndim)

1 2 3


In [ ]:
print(arr1.shape, arr2.shape,arr3.shape)

(4,) (3, 3) (2, 3, 3)


In [ ]:
print(arr1.size,arr2.size,arr3.size)

4 9 18


In [ ]:
print(arr1.dtype,arr2.dtype,arr3.dtype)

float64 int64 int64


In [ ]:
for i in arr1:
  print(i)

5.0
6.0
7.0
8.0


In [ ]:
for i in arr2:
  for j in i:
    print(j+5)

10
11
12
8
9
10
6
7
8


In [ ]:
arr4=np.array([9,8,0,6])
arr1+arr4

array([14., 14.,  7., 14.])

In [ ]:
len(arr1)

4

In [ ]:
len(arr2)

3

In [ ]:
len(arr3)

2

In [ ]:
np.unique(arr1)

array([5., 6., 7., 8.])

In [ ]:
np.unique(arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.arange(1,101).reshape((25,4))

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [ ]:
np.arange(1,101).reshape((4,25))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.arange(1,101).reshape((4,-1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.arange(1,101).reshape((-1,25))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

1* 100

100*1

25*4

4*25

In [ ]:
np.arange(1,101).reshape((-1,50))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.arange(1,101).reshape((25,2,2))


array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]],

       [[ 13,  14],
        [ 15,  16]],

       [[ 17,  18],
        [ 19,  20]],

       [[ 21,  22],
        [ 23,  24]],

       [[ 25,  26],
        [ 27,  28]],

       [[ 29,  30],
        [ 31,  32]],

       [[ 33,  34],
        [ 35,  36]],

       [[ 37,  38],
        [ 39,  40]],

       [[ 41,  42],
        [ 43,  44]],

       [[ 45,  46],
        [ 47,  48]],

       [[ 49,  50],
        [ 51,  52]],

       [[ 53,  54],
        [ 55,  56]],

       [[ 57,  58],
        [ 59,  60]],

       [[ 61,  62],
        [ 63,  64]],

       [[ 65,  66],
        [ 67,  68]],

       [[ 69,  70],
        [ 71,  72]],

       [[ 73,  74],
        [ 75,  76]],

       [[ 77,  78],
        [ 79,  80]],

       [[ 81,  82],
        [ 83,  84]],

       [[ 85,  86],
        [ 87,  88]],

       [[ 89,  90],
        [ 91,  92]],

       [[ 93,  94],
        [ 95, 

In [ ]:
np.arange(1,101).reshape((10,5,2))

array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]],

       [[ 11,  12],
        [ 13,  14],
        [ 15,  16],
        [ 17,  18],
        [ 19,  20]],

       [[ 21,  22],
        [ 23,  24],
        [ 25,  26],
        [ 27,  28],
        [ 29,  30]],

       [[ 31,  32],
        [ 33,  34],
        [ 35,  36],
        [ 37,  38],
        [ 39,  40]],

       [[ 41,  42],
        [ 43,  44],
        [ 45,  46],
        [ 47,  48],
        [ 49,  50]],

       [[ 51,  52],
        [ 53,  54],
        [ 55,  56],
        [ 57,  58],
        [ 59,  60]],

       [[ 61,  62],
        [ 63,  64],
        [ 65,  66],
        [ 67,  68],
        [ 69,  70]],

       [[ 71,  72],
        [ 73,  74],
        [ 75,  76],
        [ 77,  78],
        [ 79,  80]],

       [[ 81,  82],
        [ 83,  84],
        [ 85,  86],
        [ 87,  88],
        [ 89,  90]],

       [[ 91,  92],
        [ 93,  94],
        [ 95,  96],
        [ 97,  98],
  

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
np.resize(arr2, 4)

array([5, 6, 7, 3])

In [ ]:
np.resize(arr2, 11)

array([5, 6, 7, 3, 4, 5, 1, 2, 3, 5, 6])

In [ ]:
np.resize(arr2, (2,2))

array([[5, 6],
       [7, 3]])

In [ ]:
np.resize(arr2, (5,2))

array([[5, 6],
       [7, 3],
       [4, 5],
       [1, 2],
       [3, 5]])

In [ ]:
arr4=np.array([9,8,0,6])
arr1+arr4

array([14., 14.,  7., 14.])

In [ ]:
arr1-arr4

array([-4., -2.,  7.,  2.])

In [ ]:
arr1*2

array([10., 12., 14., 16.])

In [ ]:
arr1**2

array([25., 36., 49., 64.])

In [ ]:
score1=np.array([34,67,44,34,23])
score2=np.array([54,97,44,44,89])
score3=np.array([84,77,94,19,20])
total=score1+score2+score3


In [ ]:
average=total/3
np.round(average,2)

array([57.33, 80.33, 60.67, 32.33, 44.  ])

In [ ]:
score1+(score2-score3)

array([ 4, 87, -6, 59, 92])

In [ ]:
arr1>6

array([False, False,  True,  True])

In [ ]:
arr1

array([5., 6., 7., 8.])

In [ ]:
arr1[arr1>6]

array([7., 8.])

In [ ]:
(arr1<7).any()

np.True_

In [ ]:
(arr1<7).all()

np.False_

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2= np.reshape(arr2,(3,3))

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2>6

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
arr2[arr2>2]

array([5, 6, 7, 3, 4, 5, 3])

In [ ]:
(arr2>2).any()

np.True_

In [ ]:
arr2[arr2>2].all()

np.True_

In [ ]:
(arr2>2).all(axis=0) #column =axis=0 else axis=1

array([False, False,  True])

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2[arr2>4]

array([5, 6, 7, 5])

In [ ]:
arr2[arr2%2==0]

array([6, 4, 2])

In [ ]:
arr2[(arr2>4) & (arr2%2==0)]

array([6])

In [ ]:
arr2[(arr2>4) | (arr2%2==0)]

array([5, 6, 7, 4, 5, 2])

In [ ]:
arr2[~((arr2>4) | (arr2%2==0))]  #not(condition) = (~)

array([3, 1, 3])

In [ ]:
arr1

array([5., 6., 7., 8.])

In [ ]:
arr1[-2]

np.float64(7.0)

In [ ]:
arr1[1:3]

array([6., 7.])

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2[1,1]

np.int64(4)

In [ ]:
arr2[2,2]

np.int64(3)

In [ ]:
arr2[0:2,0:2]

array([[5, 6],
       [3, 4]])

In [ ]:
arr2[1:,1:]

array([[4, 5],
       [2, 3]])

In [ ]:
arr3

array([[[ 5,  6,  7],
        [ 3,  4,  5],
        [ 1,  2,  3]],

       [[56, 89, 45],
        [77, 33, 55],
        [12, 23, 34]]])

In [ ]:
arr3[1,0,1]

np.int64(89)

In [ ]:
arr3[0,2,1]

np.int64(2)

In [ ]:
arr3[1,0:2,1:]

array([[89, 45],
       [33, 55]])

In [ ]:
arr3[1,2,1:]

array([23, 34])

In [ ]:
arr3[0:2,2,1:]

array([[ 2,  3],
       [23, 34]])

In [ ]:
#.ipynb

In [ ]:
arr2[[0,2]]

array([[5, 6, 7],
       [1, 2, 3]])

In [ ]:
arr1.min()

np.float64(5.0)

In [ ]:
arr1.max()

np.float64(8.0)

In [ ]:
arr1.sum()

np.float64(26.0)

In [ ]:
arr1.prod()

np.float64(1680.0)

In [ ]:
arr1.mean()

np.float64(6.5)

In [ ]:
np.median(arr1)

np.float64(6.5)

In [ ]:
arr1.std()

np.float64(1.118033988749895)

In [ ]:
arr1.var()

np.float64(1.25)

In [ ]:
np.percentile(arr1,70)

np.float64(7.1)

In [ ]:
np.quantile(arr1,0.25)

np.float64(5.75)

In [ ]:
arr1.sort()

In [ ]:
arr1

array([5., 6., 7., 8.])

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2.min()

np.int64(1)

In [ ]:
arr2.min(axis=0)

array([1, 2, 3])

In [ ]:
arr2.min(axis=1)

array([5, 3, 1])

In [ ]:
arr2.sum(axis=1)

array([18, 12,  6])

In [ ]:
arr2.sort(axis=0)

In [ ]:
arr2

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [ ]:
array1=np.array([2,3,4,5])
np.dot(arr1,array1)

np.float64(96.0)

In [ ]:
arr2.T

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])