In [28]:
import numpy as np # import numpy

In [29]:
arr1=np.array([5,6,7,8],dtype=float) # create numpy 1D array

In [30]:
arr1

array([5., 6., 7., 8.])

In [31]:
type(arr1) # type of array

numpy.ndarray

In [42]:

arr2= np.array([[5,6,7],[3,4,5],[1,2,3]]) #create 2D array
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [43]:
arr3=np.array([[[5,6,7],[3,4,5],[1,2,3]],[[56,89,45],[77,33,55],[12,23,34]]]) # create 3D array
arr3

array([[[ 5,  6,  7],
        [ 3,  4,  5],
        [ 1,  2,  3]],

       [[56, 89, 45],
        [77, 33, 55],
        [12, 23, 34]]])

In [44]:
np.array([45,78,22,12,89,90] , dtype =float) #dtype The desired data-type for the array.

array([45., 78., 22., 12., 89., 90.])

In [45]:
np.array([1,0,45,78,22,90] , dtype =bool) # Here True becoz , python treats Non -zero

array([ True, False,  True,  True,  True,  True])

In [46]:
np.array([1,0,45,78,22,90] , dtype =complex)

array([ 1.+0.j,  0.+0.j, 45.+0.j, 78.+0.j, 22.+0.j, 90.+0.j])

In [47]:
# creating the indentity matrix 7x7
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [48]:
#Array Attributes

In [49]:
print(arr1.ndim, arr2.ndim,arr3.ndim)  #ndim to findout given arrays number of dimensions

1 2 3


In [50]:
print(arr1.shape, arr2.shape,arr3.shape) # shape gives each item consist of no.of rows and np.of column

(4,) (3, 3) (2, 3, 3)


In [51]:
print(arr1.size,arr2.size,arr3.size) # size gives number of items in array

4 9 18


In [52]:
print(arr1.dtype,arr2.dtype,arr3.dtype) # data types of elements in array

float64 int64 int64


In [53]:
for i in arr1:   #iteration along 1D array
  print(i)

5.0
6.0
7.0
8.0


In [54]:
for i in arr2: #iteration along 2D array
  for j in i:
    print(j+5)

10
11
12
8
9
10
6
7
8


In [55]:
len(arr1) #array length

4

In [56]:
len(arr2)

3

In [57]:
len(arr3)

2

In [58]:
np.unique(arr1) #unique elements in array

array([5., 6., 7., 8.])

In [59]:
np.unique(arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.zeros(5) #1D array of length 5 all values 0

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,3)) #2D array of 3x3 all values 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.ones(5) #1D array of length 5 all values 1

array([1., 1., 1., 1., 1.])

In [63]:
np.ones((3,3)) #3x3 array with all values 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.eye(3) #3x3 array of 0 with 1 on diagonal Identitymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.eye(3,5) #3x5 array of 0 with 1 on diagonal Identitymatrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [66]:
np.arange(5,10,2)

array([5, 7, 9])

In [67]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [68]:
np.arange(1,101).reshape((25,4)) #reshape to change dimension of an array

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [69]:
np.arange(1,101).reshape((4,25))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [70]:
np.arange(1,101).reshape((4,-1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [71]:
np.arange(1,101).reshape((-1,25))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

1* 100

100*1

25*4

4*25

In [72]:
np.arange(1,101).reshape((-1,50))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
np.arange(1,101).reshape((25,2,2))


array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]],

       [[ 13,  14],
        [ 15,  16]],

       [[ 17,  18],
        [ 19,  20]],

       [[ 21,  22],
        [ 23,  24]],

       [[ 25,  26],
        [ 27,  28]],

       [[ 29,  30],
        [ 31,  32]],

       [[ 33,  34],
        [ 35,  36]],

       [[ 37,  38],
        [ 39,  40]],

       [[ 41,  42],
        [ 43,  44]],

       [[ 45,  46],
        [ 47,  48]],

       [[ 49,  50],
        [ 51,  52]],

       [[ 53,  54],
        [ 55,  56]],

       [[ 57,  58],
        [ 59,  60]],

       [[ 61,  62],
        [ 63,  64]],

       [[ 65,  66],
        [ 67,  68]],

       [[ 69,  70],
        [ 71,  72]],

       [[ 73,  74],
        [ 75,  76]],

       [[ 77,  78],
        [ 79,  80]],

       [[ 81,  82],
        [ 83,  84]],

       [[ 85,  86],
        [ 87,  88]],

       [[ 89,  90],
        [ 91,  92]],

       [[ 93,  94],
        [ 95, 

In [74]:
np.arange(1,101).reshape((10,5,2))

array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]],

       [[ 11,  12],
        [ 13,  14],
        [ 15,  16],
        [ 17,  18],
        [ 19,  20]],

       [[ 21,  22],
        [ 23,  24],
        [ 25,  26],
        [ 27,  28],
        [ 29,  30]],

       [[ 31,  32],
        [ 33,  34],
        [ 35,  36],
        [ 37,  38],
        [ 39,  40]],

       [[ 41,  42],
        [ 43,  44],
        [ 45,  46],
        [ 47,  48],
        [ 49,  50]],

       [[ 51,  52],
        [ 53,  54],
        [ 55,  56],
        [ 57,  58],
        [ 59,  60]],

       [[ 61,  62],
        [ 63,  64],
        [ 65,  66],
        [ 67,  68],
        [ 69,  70]],

       [[ 71,  72],
        [ 73,  74],
        [ 75,  76],
        [ 77,  78],
        [ 79,  80]],

       [[ 81,  82],
        [ 83,  84],
        [ 85,  86],
        [ 87,  88],
        [ 89,  90]],

       [[ 91,  92],
        [ 93,  94],
        [ 95,  96],
        [ 97,  98],
  

In [75]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [76]:
np.resize(arr2, 4) #resize number of elements in array and give a one dimensional array

array([5, 6, 7, 3])

In [77]:
np.resize(arr2, 11)

array([5, 6, 7, 3, 4, 5, 1, 2, 3, 5, 6])

In [78]:
np.resize(arr2, (2,2)) #resize number of elements in array and give a 2D dimensional array

array([[5, 6],
       [7, 3]])

In [79]:
np.resize(arr2, (5,2))

array([[5, 6],
       [7, 3],
       [4, 5],
       [1, 2],
       [3, 5]])

In [80]:
# Mathematical operation (vector operations )

In [81]:
arr4=np.array([9,8,0,6])
arr1+arr4

array([14., 14.,  7., 14.])

In [82]:
arr1-arr4

array([-4., -2.,  7.,  2.])

In [83]:
arr1*2

array([10., 12., 14., 16.])

In [84]:
arr1**2

array([25., 36., 49., 64.])

In [85]:
#find average of scores of students
score1=np.array([34,67,44,34,23])
score2=np.array([54,97,44,44,89])
score3=np.array([84,77,94,19,20])
total=score1+score2+score3
average=total/3
print(f" Average marks of students {np.round(average,2)}")


 Average marks of students [57.33 80.33 60.67 32.33 44.  ]


In [86]:
score1+(score2-score3)

array([ 4, 87, -6, 59, 92])

In [87]:
#Boolean operation with array

In [88]:
arr1>6 # return array elemnets with boolean values which is true for the statement

array([False, False,  True,  True])

In [89]:
arr1[arr1>6] # return array elemnets with actual values which is true for the statement

array([7., 8.])

In [90]:
(arr1<7).any() # return a boolean value if any values statisfies the condition

np.True_

In [91]:
(arr1<7).all() # return a boolean value if all values statisfies the condition

np.False_

In [92]:
arr2= np.reshape(arr2,(3,3)) # reshape an array of 3x3

In [93]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [94]:
arr2>6  # return 2D array of elemnets with boolean values which is  true for the statement

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [95]:
arr2[arr2>2] # return array elemnets with actual values which true for the statement from 2D

array([5, 6, 7, 3, 4, 5, 3])

In [96]:
(arr2>2).any()  # return a boolean value if any values statisfies the condition

np.True_

In [ ]:
arr2[arr2>2].all() # return a boolean value if all values statisfies the condition

np.True_

In [97]:
(arr2>2).all(axis=0)   # return a array of  boolean values if all values statisfies the condition along columns
#column =axis=0 else axis=1

array([False, False,  True])

In [98]:
# Logical  operation on array

In [99]:
arr2[arr2>4]

array([5, 6, 7, 5])

In [100]:
arr2[arr2%2==0]

array([6, 4, 2])

In [101]:
arr2[(arr2>4) & (arr2%2==0)] #  'and' operator to check if two or more statements are satisfies in an array

array([6])

In [102]:
arr2[(arr2>4) | (arr2%2==0)] #  'or' operator to check if two or more statements are satisfies in an array

array([5, 6, 7, 4, 5, 2])

In [103]:
arr2[~((arr2>4) | (arr2%2==0))] #  'not' operator to reverse a statement  in  an array
 #not(condition) = (~)

array([3, 1, 3])

In [104]:
arr2[~((arr2>4) )| (arr2%2==0)]

array([6, 3, 4, 1, 2, 3])

In [105]:
arr2[(arr2>4) | ~((arr2%2==0))]

array([5, 6, 7, 3, 5, 1, 3])

In [ ]:
#Array element accessing  and slicing

In [ ]:
arr1[2] #index - positive

In [106]:
arr1[-2] #index - negative

np.float64(7.0)

In [107]:
arr1[1:3] #start: stop

array([6., 7.])

In [ ]:
arr2[1,1] # array element accesing - 1- array value, 1- column value

np.int64(4)

In [ ]:
arr2[2,2] #2- array value, 2- column value

np.int64(3)

In [ ]:
arr2[0:2,0:2] #2D slicing

array([[5, 6],
       [3, 4]])

In [ ]:
arr2[1:,1:]

array([[4, 5],
       [2, 3]])

In [ ]:
arr3 #3D array sclicing

array([[[ 5,  6,  7],
        [ 3,  4,  5],
        [ 1,  2,  3]],

       [[56, 89, 45],
        [77, 33, 55],
        [12, 23, 34]]])

In [ ]:
arr3[1,0,1] # 1- block, 0- row, 1- column

np.int64(89)

In [ ]:
arr3[0,2,1]

np.int64(2)

In [ ]:
arr3[1,0:2,1:] #3D slicing

array([[89, 45],
       [33, 55]])

In [ ]:
arr3[1,2,1:]

array([23, 34])

In [ ]:
arr3[0:2,2,1:]

array([[ 2,  3],
       [23, 34]])

In [ ]:
arr2[[0,2]] # array row accessing

array([[5, 6, 7],
       [1, 2, 3]])

In [ ]:
#array functions

In [ ]:
arr1.min()

np.float64(5.0)

In [ ]:
arr1.max()

np.float64(8.0)

In [ ]:
arr1.sum()

np.float64(26.0)

In [ ]:
arr1.prod()

np.float64(1680.0)

In [ ]:
arr1.mean()

np.float64(6.5)

In [ ]:
np.median(arr1)

np.float64(6.5)

In [ ]:
arr1.std()

np.float64(1.118033988749895)

In [ ]:
arr1.var()

np.float64(1.25)

In [ ]:
np.percentile(arr1,70)

np.float64(7.1)

In [ ]:
np.quantile(arr1,0.25)

np.float64(5.75)

In [ ]:
arr1.sort()

In [ ]:
arr1

array([5., 6., 7., 8.])

In [ ]:
arr2

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [ ]:
arr2.min()

np.int64(1)

In [ ]:
arr2.min(axis=0)  # min along columns

array([1, 2, 3])

In [ ]:
arr2.min(axis=1)  # sum along row

array([5, 3, 1])

In [ ]:
arr2.sum(axis=1) # sum along tow

array([18, 12,  6])

In [ ]:
arr2.sort(axis=0)  # sort  along columns

In [ ]:
arr2

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [ ]:
array1=np.array([2,3,4,5])
np.dot(arr1,array1)  #vector dot product

np.float64(96.0)

In [ ]:
arr2.T #vector transpose

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])